import React,{useMemo,useState}from 'react'
const BLUE='#0047BA',AQUA='#2FC2B6',CODE='FINBROADPEAK26',CB=.04,JUAN='https://i.imgur.com/LfWe8VX.png'
const u=id=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`
const P={Souvenirs:u('photo-1528283648649-33347faa5d9b'),Ferreteria:u('photo-1504148455328-c376907d081c'),Dulces:u('photo-1582058091505-f87a2e55a40f'),Cultura:u('photo-1512820790803-83ca734da794'),Moda:u('photo-1445205170230-053b83016050'),Gourmet:u('photo-1542838132-92c53300491e'),Tecnologia:u('photo-1516321318423-f06f85e504b3'),Belleza:u('photo-1596462502278-27bfdc403348'),Deporte:u('photo-1517649763962-0c623066013b'),Mascotas:u('photo-1601758228041-f3b2795255f1'),Ocio:u('photo-1500530855697-b586d89ba3ee'),Flores:u('photo-1490750967868-88aa4486c946'),Bicicletas:u('photo-1485965120184-e220f721d03e'),Juguetes:u('photo-1558060370-d644479cb6f7'),Cafes:u('photo-1495474472287-4d71bcdd2085'),Papeleria:u('photo-1455390582262-044cdead277a'),Calzado:u('photo-1542291026-7eec264c27ff'),Herbolario:u('photo-1514995669114-6081e934b693'),Merceria:u('photo-1452860606245-08befc0ff44b'),Optica:u('photo-1574258495973-f010dfbb5371'),Fotografia:u('photo-1492691527719-9d1e07e534b4'),Ceramica:u('photo-1493106819501-66d381c466f1'),Regalos:u('photo-1513201099705-a9746e1e201f'),EcoMarket:u('photo-1542838132-92c53300491e'),Bienestar:u('photo-1540555700478-4be289fbecef')}
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace('í','i')
const imgFor=s=>P[norm(s).replace('Tecnologia','Tecnologia').replace('Ferreteria','Ferreteria').replace('Cafes','Cafes').replace('Optica','Optica').replace('Fotografia','Fotografia').replace('Ceramica','Ceramica').replace('Papeleria','Papeleria').replace('Merceria','Merceria')]||P.Gourmet
const rows=`Souvenirs La Rambla|Souvenirs|Barcelona|La Rambla, 45|Imán 3,50€;Taza 8,90€;Postal 1,50€;Bolsa 9,95€;Abanico 12,90€;Llavero 4,50€
Ferretería Ferran|Ferretería|Barcelona|La Rambla, 102|Pinzas 0,99€;Cinta 4,95€;Destornillador 5,50€
Gominolas Happy Ring|Dulces|Barcelona|La Rambla, 78|Anillo 0,35€;Mix 3,95€;Regaliz 1,50€;Nubes 2,20€;Lenguas 2,50€;Piruleta 1,20€;Moras 2,10€
Casa Beethoven|Cultura|Barcelona|La Rambla, 97|Partitura 12,90€;Cuaderno 6,95€;Libro 18,50€;Marcapáginas 2,50€
La Manual Alpargatera|Moda|Barcelona|La Rambla, 71|Alpargata 49€;Cuña 69€;Pañuelo 19,90€;Bolsa 14,90€;Plantillas 9,90€
Casa Gispert|Gourmet|Barcelona|La Rambla, 36|Almendra 7,80€;Café 6,90€;Chocolate 5,50€;Avellanas 8,20€;Pack 24,90€;Té 4,50€;Miel 7,20€
Vila Viniteca|Gourmet|Barcelona|La Rambla, 121|Aceite 14,90€;Queso 9,80€;Paté 6,50€
Llibreria Finestres|Cultura|Barcelona|La Rambla, 64|Novela 21,90€;Ensayo 19,50€;Libreta 8,95€;Agenda 16,90€;Poesía 14,90€;Infantil 13,50€
Norma Comics|Cultura|Barcelona|La Rambla, 88|Manga 8,95€;Cómic 24€;Figura 19,90€;Póster 7,50€;Merch 14,90€
TecnoBarri|Tecnología|Barcelona|La Rambla, 110|Cable 9,95€;Cargador 19,90€;Soporte 12,50€;Powerbank 24,90€;Auriculares 29,90€;Ratón 16,95€;Teclado 29,90€;Hub 22€
Bits del Raval|Tecnología|Barcelona|La Rambla, 52|Auriculares 14,90€;Ratón 16,95€;HDMI 11,90€
Colmado Quílez|Gourmet|Barcelona|La Rambla, 95|Mermelada 5,95€;Aceitunas 4,50€;Galletas 6,90€;Vermut 8,95€;Pack 22,90€
Ferretería del Born|Ferretería|Barcelona|La Rambla, 134|Cinta 2,20€;Llave 9,95€;Guantes 4,50€;Bridas 1,95€;Cola 5,80€;Linterna 8,90€
Candy Barcelona|Dulces|Barcelona|La Rambla, 29|Moras 2,50€;Piruleta 1,20€;Bolsa 4,50€
Souvenirs Catalunya|Souvenirs|Barcelona|La Rambla, 56|Imán 3,95€;Taza 8,90€;Abanico 12,90€;Postal 5€;Camiseta 14,90€;Llavero 4,50€
Cosmètica del Gòtic|Belleza|Barcelona|La Rambla, 83|Crema 8,95€;Bálsamo 4,50€;Jabón 5,90€;Pack 29,90€;Aceite 14,90€;Sérum 19,90€;Mascarilla 6,90€
Esport Canuda|Deporte|Barcelona|La Rambla, 118|Calcetines 9,95€;Bidón 14,90€;Cinta 6,50€;Pelotas 7,95€
Mascotes Glòries|Mascotas|Barcelona|La Rambla, 67|Snack 3,95€;Juguete 7,50€;Champú 9,90€;Correa 12,90€;Arena 8,95€;Comedero 6,90€
Experiències Gràcia|Ocio|Barcelona|La Rambla, 140|Taller 29€;Ruta 14€;Cata 22€;Escape 18€;Actividad 25€
Floristería Eixample|Flores|Barcelona|La Rambla, 22|Ramo 18€;Planta 12,90€;Rosa 4,50€;Maceta 9,95€;Centro 29€
Rocambolesc Girona|Dulces|Girona|Carrer Santa Clara, 50|Helado 4,50€;Caramelo 3,20€;Topping 1,50€;Pack 12,90€;Chocolate 5,50€
Llibreria 22|Cultura|Girona|Carrer Hortes, 22|Novela 10,95€;Infantil 14,90€;Cuaderno 7,95€
Mercat Central Tarragona|Gourmet|Tarragona|Plaça Corsini, 1|Aceite 11,90€;Avellanas 6,95€;Conserva 8,50€;Miel 7,20€;Pack 27,90€;Embutido 9,80€
La Fatal|Cultura|Lleida|Carrer Vallcalent, 65|Ensayo 16,90€;Poesía 13,50€;Agenda 12,90€;Lámina 9,95€;Revista 6,50€
Papereria Sabadell|Papelería|Sabadell|Carrer de Gràcia, 12|Bolígrafo 3,95€;Libreta 5,50€;Carpeta 4,20€
Ferretería Terrassa|Ferretería|Terrassa|Carrer Major, 88|Alcayatas 2,90€;Pilas 4,50€;Llave Allen 3,20€;Metro 6,95€;Linterna 8,90€
Mercat Collblanc|Gourmet|Hospitalet|Carrer Occident, 12|Café 7,50€;Queso 4,90€;Fuet 5,95€;Pan 3,20€
Taller Màgic Badalona|Ocio|Badalona|Carrer del Mar, 34|Taller 12€;Kit 9,95€;Clase 25€;Entrada 15€;Show 20€
Mercat Mataró|Gourmet|Mataró|Plaça Cuba, 47|Miel 6,90€;Aceite 10,95€;Galletas 5,50€
Gominoles Reus|Dulces|Reus|Carrer Monterols, 15|Mix 3,50€;Anillo 0,35€;Moras 2,20€;Pack 14,90€;Piruletas 1€
Souvenir Sitges|Souvenirs|Sitges|Carrer del Pecat, 8|Pulsera 5,95€;Imán 3,50€;Toalla 18,90€;Postal 1,50€;Bolsa playa 14,90€
Bicis Poblenou|Bicicletas|Barcelona|Carrer Pere IV, 210|Cámara 6,95€;Luces 14,90€;Timbre 7,50€;Casco 39,90€;Candado 19,90€;Bidón 9,90€;Kit reparación 12,90€
Joguines Sant Antoni|Juguetes|Barcelona|Comte Borrell, 45|Puzzle 12,90€;Peluche 9,95€;Cartas 8,50€;Peonza 4,95€
Cafès del Clot|Cafés|Barcelona|Carrer del Clot, 92|Café 8,90€;Filtro 3,50€;Taza 7,95€
Papereria Les Corts|Papelería|Barcelona|Travessera Corts, 198|Bloc 3,20€;Bolígrafos 4,95€;Subrayadores 5,50€;Archivador 3,95€;Corrector 2,80€;Agenda 12,95€
Sabateria Sarrià|Calzado|Barcelona|Major Sarrià, 76|Plantillas 9,95€;Cordones 3,50€;Crema 5,90€;Cepillo 6,95€;Calzador 4,50€
Herbolari Horta|Herbolario|Barcelona|Carrer Horta, 61|Infusión 4,95€;Aceite 8,90€;Jabón 5,50€;Crema 9,95€
Merceria Sants|Mercería|Barcelona|Carrer de Sants, 133|Hilo 2,20€;Botones 1,95€;Cremallera 3,50€;Agujas 2,80€
Òptica Marina|Óptica|Barcelona|Pg. Maragall, 120|Gamuza 2,50€;Spray 5,95€;Funda 6,90€;Cordón 4,50€;Kit limpieza 9,90€
Foto Gràcia|Fotografía|Barcelona|Gran de Gràcia, 145|Revelado 4,90€;Marco 6,50€;Álbum 12,90€;SD 9,95€;Impresión 10€
Ceràmica Vic|Cerámica|Vic|Carrer Riera, 9|Taza 14,90€;Plato 22€;Cuenco 16,50€;Posavasos 9,95€
Esports Manresa|Deporte|Manresa|Pg. Pere III, 55|Muñequera 5,95€;Grip 7,50€;Botella 9,90€;Pack pádel 18,90€;Toalla 12,90€
Dolços Figueres|Dulces|Figueres|Rambla, 23|Galletas 4,95€;Caramelos 3,20€;Chocolate 5,90€
Ferreteria Olot|Ferretería|Olot|Carrer Major, 17|Tornillos 2,95€;Cúter 4,50€;Brocha 3,20€;Silicona 6,95€
Llibres Vic|Cultura|Vic|Plaça Major, 12|Novela 19,90€;Infantil 13,95€;Libreta 6,90€;Marcapáginas 2€;Agenda 12€
Mascotes Girona Nord|Mascotas|Girona|Av. Jaume I, 30|Pelota 4,95€;Snack 3,50€;Comedero 8,90€;Collar 6,95€;Champú 9,90€
Regals Cambrils|Regalos|Cambrils|Pg. Miramar, 5|Imán 3,50€;Pulsera 4,90€;Taza 8,50€
EcoMarket Rubí|EcoMarket|Rubí|Carrer Maximí Fornés, 21|Pasta eco 3,95€;Miel 7,50€;Granola 5,90€;Pack 19,90€;Té 4,50€
Jocs Granollers|Juguetes|Granollers|Anselm Clavé, 44|Juego mesa 24,90€;Cartas 8,95€;Puzzle 15,90€;Plastilina 4,50€;Lego compatible 19,90€
Benestar Tarragona|Bienestar|Tarragona|Rambla Nova, 101|Sales 6,50€;Vela 9,95€;Masaje 32€;Pack relax 24,90€;Aceite 11,90€`
function item(s,i,j){const m=s.match(/(.+)\s(\d+(?:,\d+)?)€$/),name=(m?m[1]:s).trim(),price=m?Number(m[2].replace(',','.')):0;return{id:`p${i}-${j}`,name,price,description:`${name} disponible en tienda.`,img:P.Gourmet}}
const merchants=rows.split('\n').map((r,i)=>{const [name,sector,city,address,items]=r.split('|');return{id:`m${i}`,name,sector,city,address,community:'Cataluña',products:items.split(';').map((x,j)=>item(x,i,j)),image:imgFor(sector),distance:city==='Barcelona'?+(0.2+i*.23).toFixed(1):70+i*2,rating:(4.2+(i%8)/10).toFixed(1),reviews:80+i*17,open:i%5!==0,promo:i<15||i%7===0,highlighted:i<12||i%11===0,promoText:name.includes('Ferretería Ferran')?'Pinzas en promo':name.includes('Gominolas Happy')?'Anillo de caramelo en promo':i%2?`Cupón ${CODE}`:'Semana del comercio: -5%'}})
const sectors=[...new Set(merchants.map(m=>m.sector))],cities=[...new Set(merchants.map(m=>m.city))]
const txt={es:{explore:'Explorar',promos:'Promociones',how:'Cómo funciona',trade:'Para comercios',account:'Mi cuenta',cart:'Carrito',hero:'Compra local en Cataluña con beneficios CaixaBank',sub:'Descubre comercios cerca de ti, compra online, reserva servicios y acumula cashback apoyando tu barrio.',search:'Busca souvenirs, ferreterías, gominolas, librerías...',weekly:'Promociones de la semana',near:'Cerca de ti ahora',featured:'Comercios más relevantes'},ca:{explore:'Explorar',promos:'Promocions',how:'Com funciona',trade:'Per a comerços',account:'El meu compte',cart:'Cistella',hero:'Compra local a Catalunya amb beneficis CaixaBank',sub:'Descobreix comerços a prop teu, compra en línia i acumula cashback.',search:'Busca souvenirs, ferreteries, llaminadures...',weekly:'Promocions de la setmana',near:'A prop teu ara',featured:'Comerços més rellevants'}}
function FlagCat(){return <span className='inline-block w-5 h-3 rounded-sm border' style={{background:'repeating-linear-gradient(0deg,#f6d447 0 3px,#c9252d 3px 5px)'}}/>}
function Logo(){return <div className='leading-none'><div className='text-3xl font-black'>facilitea <span style={{color:AQUA}}>GO</span></div><div className='-mt-1 text-right text-xs font-bold text-zinc-700'>by CaixaBank</div></div>}
function Header({page,setPage,cart,lang,setLang}){const t=txt[lang];return <header className='sticky top-0 z-40 bg-white/90 backdrop-blur border-b'><div className='max-w-7xl mx-auto px-4 py-3 flex items-center justify-between gap-3'><button onClick={()=>setPage('home')}><Logo/></button><nav className='hidden lg:flex gap-1'>{[['explore',t.explore],['promos',t.promos],['how',t.how],['merchants',t.trade]].map(([k,l])=><button key={k} onClick={()=>setPage(k)} className={`px-4 py-2 rounded-full font-bold text-sm ${page===k?'bg-zinc-100':'text-zinc-600'}`}>{l}</button>)}</nav><div className='flex gap-2 items-center'><button onClick={()=>setLang('es')} className={`px-3 py-2 rounded-full border font-bold text-sm ${lang==='es'?'text-white':''}`} style={lang==='es'?{backgroundColor:BLUE}:{}}>🇪🇸 ES</button><button onClick={()=>setLang('ca')} className={`px-3 py-2 rounded-full border font-bold text-sm flex items-center gap-1 ${lang==='ca'?'text-white':''}`} style={lang==='ca'?{backgroundColor:BLUE}:{}}><FlagCat/> CAT</button><button onClick={()=>setPage('account')} className='hidden sm:flex px-3 py-2 rounded-full border font-bold'>{t.account}</button><button onClick={()=>setPage('cart')} className='relative px-4 py-2 rounded-full text-white font-bold' style={{backgroundColor:BLUE}}>🛍 {t.cart}{cart>0&&<span className='absolute -top-2 -right-2 w-6 h-6 rounded-full bg-teal-400 grid place-items-center text-xs'>{cart}</span>}</button></div></div></header>}
function Search({q,setQ,setPage,lang}){return <div className='bg-white rounded-3xl p-2 shadow-xl border flex flex-col md:flex-row gap-2'><div className='flex-1 px-4 py-3'>⌕ <input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&setPage('explore')} placeholder={txt[lang].search} className='w-[90%] outline-none'/></div><div className='px-4 py-3 bg-zinc-50 rounded-2xl font-bold text-sm'>⌖ Las Ramblas, Barcelona</div><button onClick={()=>setPage('explore')} className='px-6 py-3 rounded-2xl text-white font-black' style={{backgroundColor:BLUE}}>Buscar</button></div>}
function Card({m,open,add}){return <div className='bg-white rounded-3xl border shadow-sm overflow-hidden transition hover:-translate-y-1'><div className='relative h-44'><img src={m.image} className='w-full h-full object-cover'/><div className='absolute inset-0 bg-gradient-to-t from-black/65 to-transparent'/>{m.promo&&<span className='absolute top-3 left-3 px-3 py-1 rounded-full text-xs font-black text-white' style={{backgroundColor:AQUA}}>{m.promoText}</span>}<div className='absolute bottom-4 left-4 text-white'><div className='font-black text-lg'>{m.name}</div><div className='text-xs'>{m.city}</div></div></div><div className='p-5'><div className='flex justify-between mb-3'><span className='text-xs font-bold bg-zinc-100 rounded-full px-3 py-1'>{m.sector}</span><span className='font-bold text-sm text-amber-500'>★ {m.rating}</span></div><div className='text-sm text-zinc-600'>⌖ {m.address}</div><div className='mt-3 flex flex-wrap gap-2'><b className='text-xs text-blue-700 bg-blue-50 px-2 py-1 rounded-full'>{m.distance} km</b><b className='text-xs text-teal-700 bg-teal-50 px-2 py-1 rounded-full'>4% cashback</b>{m.open&&<b className='text-xs text-emerald-700 bg-emerald-50 px-2 py-1 rounded-full'>Abierto</b>}</div><p className='mt-3 text-sm text-zinc-500'>Compra, reserva y acumula puntos faciliteaGO.</p><div className='mt-5 flex gap-2'><button onClick={()=>open(m)} className='flex-1 px-4 py-3 rounded-2xl border font-bold'>Ver local</button><button onClick={()=>add(m,m.products[0])} className='px-4 py-3 rounded-2xl text-white font-bold' style={{backgroundColor:BLUE}}>+</button></div></div></div>}
function Section({title,desc,children}){return <section className='max-w-7xl mx-auto px-4 py-14'><h2 className='text-3xl font-black'>{title}</h2><p className='text-zinc-500 mt-1 mb-6'>{desc}</p>{children}</section>}
function Home({q,setQ,setPage,open,add,lang}){const t=txt[lang],promos=merchants.filter(m=>m.promo).slice(0,4),near=merchants.filter(m=>m.city==='Barcelona').slice(0,6),feat=merchants.filter(m=>m.highlighted).slice(0,8);return <main><section className='bg-gradient-to-br from-blue-50 via-white to-teal-50'><div className='max-w-7xl mx-auto px-4 py-16 lg:py-24 grid lg:grid-cols-2 gap-12 items-center'><div><div className='inline-flex px-4 py-2 rounded-full bg-white border font-bold text-blue-800'>✦ Marketplace local</div><h1 className='mt-6 text-5xl md:text-7xl font-black leading-[.92]'>{t.hero}</h1><p className='mt-6 text-xl text-zinc-600'>{t.sub}</p><div className='mt-8'><Search q={q} setQ={setQ} setPage={setPage} lang={lang}/></div><div className='mt-5 flex gap-3 font-bold flex-wrap'><span>✓ Compra segura</span><span>% {CODE}</span><span>🎁 4% cashback</span></div></div><div className='grid grid-cols-2 gap-4'><div className='space-y-4 pt-10'>{promos.slice(0,2).map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div><div className='space-y-4'><div className='rounded-[2rem] bg-white p-5 shadow-xl border'><div className='flex gap-3'><img src={JUAN} className='w-16 h-16 rounded-2xl object-contain'/><div><b className='text-xl'>JuanIA</b><p className='text-sm text-zinc-600'>Te preparo una ruta con cashback.</p></div></div><button onClick={()=>setPage('explore')} className='mt-4 w-full rounded-2xl py-3 text-white font-bold' style={{backgroundColor:BLUE}}>Ver ruta</button></div>{promos.slice(2,4).map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></div></div></section><Section title={t.weekly} desc={`Cupón ${CODE}, cashback CaixaBank y productos de barrio.`}><div className='grid md:grid-cols-2 lg:grid-cols-4 gap-5'>{promos.map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></Section><Section title={t.near} desc='Comercios cerca de Las Ramblas.'><div className='grid md:grid-cols-2 lg:grid-cols-3 gap-5'>{near.map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></Section><Section title={t.featured} desc='Selección por cercanía, promoción y relevancia.'><div className='grid md:grid-cols-2 lg:grid-cols-4 gap-5'>{feat.map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></Section></main>}
function Explore({q,setQ,open,add,lang}){const [sector,setSector]=useState('Todos'),[city,setCity]=useState('Todos'),[promo,setPromo]=useState(false),[isOpen,setIsOpen]=useState(false);const list=useMemo(()=>merchants.filter(m=>{const s=q.toLowerCase(),hay=(m.name+' '+m.sector+' '+m.city+' '+m.address+' '+m.products.map(p=>p.name).join(' ')).toLowerCase();return(!s||hay.includes(s))&&(sector==='Todos'||m.sector===sector)&&(city==='Todos'||m.city===city)&&(!promo||m.promo)&&(!isOpen||m.open)}),[q,sector,city,promo,isOpen]);return <main className='max-w-7xl mx-auto px-4 py-8'><div className='rounded-[2rem] bg-gradient-to-br from-blue-50 to-teal-50 p-6 border'><h1 className='text-4xl font-black'>Explorar</h1><div className='mt-6'><Search q={q} setQ={setQ} setPage={()=>{}} lang={lang}/></div><div className='mt-5 grid md:grid-cols-3 gap-3'><select value={sector} onChange={e=>setSector(e.target.value)} className='rounded-2xl border px-4 py-3 font-bold'><option>Todos</option>{sectors.map(s=><option key={s}>{s}</option>)}</select><select className='rounded-2xl border px-4 py-3 font-bold'><option>Cataluña</option></select><select value={city} onChange={e=>setCity(e.target.value)} className='rounded-2xl border px-4 py-3 font-bold'><option>Todos</option>{cities.map(c=><option key={c}>{c}</option>)}</select></div><div className='mt-4 flex gap-2'><button onClick={()=>setPromo(!promo)} className={`px-4 py-2 rounded-full border font-bold ${promo?'text-white':'bg-white'}`} style={promo?{backgroundColor:BLUE}:{}}>Con promoción</button><button onClick={()=>setIsOpen(!isOpen)} className={`px-4 py-2 rounded-full border font-bold ${isOpen?'text-white':'bg-white'}`} style={isOpen?{backgroundColor:BLUE}:{}}>Abierto ahora</button></div></div><div className='mt-6 flex justify-between'><b>{list.length} resultados</b><span className='text-sm text-zinc-500'>Cupón activo: {CODE}</span></div><div className='mt-6 grid md:grid-cols-2 lg:grid-cols-4 gap-5'>{list.map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></main>}
function Merchant({m,setPage,add}){const[p,setP]=useState(m.products[0]);return <main><section className='relative h-[360px]'><img src={m.image} className='w-full h-full object-cover'/><div className='absolute inset-0 bg-gradient-to-t from-black/80 to-transparent'/><div className='absolute inset-x-0 bottom-0 max-w-7xl mx-auto px-4 pb-8 text-white'><button onClick={()=>setPage('explore')} className='mb-5 px-4 py-2 rounded-full bg-white/20 font-bold'>← Volver</button><h1 className='text-5xl font-black'>{m.name}</h1><p>⌖ {m.address}, {m.city} · ★ {m.rating}</p></div></section><section className='max-w-7xl mx-auto px-4 py-10 grid lg:grid-cols-[1fr_360px] gap-8'><div><h2 className='text-3xl font-black'>Productos y servicios</h2><div className='mt-6 grid gap-3'>{m.products.map(x=><button key={x.id} onClick={()=>setP(x)} className={`text-left rounded-3xl border p-4 ${p.id===x.id?'border-blue-500 bg-blue-50':'bg-white'}`}><div className='flex items-center justify-between gap-4'><div className='flex items-center gap-4'><img src={x.img} className='w-20 h-20 rounded-2xl object-cover bg-zinc-100'/><div><b className='text-lg'>{x.name}</b><p className='text-sm text-zinc-500'>{x.description}</p></div></div><b className='text-xl text-blue-700 whitespace-nowrap'>{x.price.toFixed(2)}€</b></div></button>)}</div></div><aside className='h-fit rounded-[2rem] bg-white border shadow-xl p-6'><h3 className='text-2xl font-black'>Resumen</h3><div className='mt-4 bg-zinc-50 rounded-3xl p-4'><img src={p.img} className='w-20 h-20 rounded-2xl object-cover'/><b className='block mt-3'>{p.name}</b><div className='mt-2 text-3xl font-black'>{p.price.toFixed(2)}€</div></div><div className='mt-4 text-sm flex justify-between'><span>Cashback</span><b>{(p.price*CB).toFixed(2)}€</b></div><button onClick={()=>add(m,p)} className='mt-6 w-full py-4 rounded-2xl text-white font-black' style={{backgroundColor:BLUE}}>Añadir al carrito</button></aside></section></main>}
function Cart({cart,setCart,setPage}){const total=cart.reduce((s,i)=>s+i.product.price*i.qty,0)*.93;return <main className='max-w-5xl mx-auto px-4 py-10'><h1 className='text-4xl font-black'>Carrito</h1>{cart.length===0?<div className='mt-6 rounded-3xl bg-zinc-50 p-10'>Tu carrito está vacío.</div>:<div className='mt-6 grid gap-4'>{cart.map(i=><div key={i.id} className='rounded-3xl border p-4 flex gap-4'><img src={i.product.img} className='w-20 h-20 rounded-2xl object-cover'/><div className='flex-1'><b>{i.product.name}</b><div className='text-sm text-zinc-500'>{i.merchant.name}</div></div><b>{(i.product.price*i.qty).toFixed(2)}€</b></div>)}<div className='text-right text-3xl font-black'>Total {total.toFixed(2)}€</div><button onClick={()=>setPage('checkout')} className='ml-auto px-6 py-4 rounded-2xl text-white font-black' style={{backgroundColor:BLUE}}>Pagar</button></div>}</main>}
function Checkout({cart,setCart,setPage,setOrders}){const total=cart.reduce((s,i)=>s+i.product.price*i.qty,0)*.93;return <main className='min-h-[70vh] grid place-items-center p-4'><div className='max-w-xl rounded-[2rem] bg-white border shadow-xl p-8 text-center'><h1 className='text-4xl font-black'>Pago seguro</h1><p className='mt-3 text-zinc-600'>Pasarela simulada sin datos bancarios reales.</p><button onClick={()=>{setOrders(o=>[{id:'FG-'+Date.now().toString().slice(-6),date:new Date().toLocaleDateString(),total,items:cart},...o]);setCart([]);setPage('account')}} className='mt-6 px-6 py-4 rounded-2xl text-white font-black' style={{backgroundColor:BLUE}}>Confirmar pago {total.toFixed(2)}€</button></div></main>}
function Account({orders,setPage}){return <main className='max-w-5xl mx-auto px-4 py-10'><h1 className='text-4xl font-black'>Mi cuenta</h1><div className='mt-6 grid md:grid-cols-3 gap-4'><div className='rounded-3xl p-6 text-white' style={{backgroundColor:BLUE}}><span>Cashback acumulado</span><b className='block text-4xl'>42,80€</b></div><div className='rounded-3xl p-6 text-white' style={{backgroundColor:AQUA}}><span>Puntos faciliteaGO</span><b className='block text-4xl'>1240</b></div><div className='rounded-3xl p-6 text-white bg-zinc-950'><span>Favoritos</span><b className='block text-4xl'>18</b></div></div><h2 className='mt-8 text-2xl font-black'>Mis compras</h2>{orders.length===0?<p className='mt-3 text-zinc-500'>Aún no hay compras finalizadas.</p>:orders.map(o=><div key={o.id} className='mt-3 rounded-3xl border p-4'><b>{o.id}</b><div>{o.date} · {o.total.toFixed(2)}€</div></div>)}</main>}
function JuanIA({setQ,open}){const[show,setShow]=useState(false),[msg,setMsg]=useState('Soy JuanIA. Busca pinzas, anillos, souvenirs o rutas.');return <>{show&&<div className='fixed right-5 bottom-24 z-50 w-[420px] max-w-[calc(100vw-40px)] rounded-[2rem] bg-white border shadow-2xl overflow-hidden'><div className='p-5 text-white flex gap-4 items-center' style={{backgroundColor:BLUE}}><img src={JUAN} className='w-16 h-16 rounded-2xl object-contain bg-white'/><div><b>JuanIA</b><p>Asistente de compra local</p></div><button className='ml-auto' onClick={()=>setShow(false)}>×</button></div><div className='p-4'><p>{msg}</p><div className='mt-4 flex flex-wrap gap-2'>{['Pinzas','Anillo de caramelo','Souvenirs','Ruta por Las Ramblas'].map(x=><button key={x} onClick={()=>{setQ(x);setMsg(`Te muestro locales relacionados con ${x}.`)}} className='text-xs font-bold px-3 py-2 rounded-full bg-zinc-100'>{x}</button>)}</div></div></div>}<button onClick={()=>setShow(true)} className='fixed right-5 bottom-5 z-50 w-16 h-16 rounded-full text-white shadow-2xl' style={{backgroundColor:BLUE}}>💬</button></>}
export default function App(){const[page,setPage]=useState('home'),[lang,setLang]=useState('es'),[q,setQ]=useState(''),[sel,setSel]=useState(merchants[0]),[cart,setCart]=useState([]),[orders,setOrders]=useState([]);const open=m=>{setSel(m);setPage('merchant');scrollTo(0,0)},add=(merchant,product)=>setCart(c=>[...c,{id:merchant.id+product.id+Date.now(),merchant,product,qty:1}]);return <div className='min-h-screen bg-white text-zinc-950' style={{fontFamily:'Inter,Quicksand,system-ui,sans-serif'}}><Header page={page} setPage={setPage} cart={cart.length} lang={lang} setLang={setLang}/>{page==='home'&&<Home q={q} setQ={setQ} setPage={setPage} open={open} add={add} lang={lang}/>} {page==='explore'&&<Explore q={q} setQ={setQ} open={open} add={add} lang={lang}/>} {page==='merchant'&&<Merchant m={sel} setPage={setPage} add={add}/>} {page==='cart'&&<Cart cart={cart} setCart={setCart} setPage={setPage}/>} {page==='checkout'&&<Checkout cart={cart} setCart={setCart} setPage={setPage} setOrders={setOrders}/>} {page==='account'&&<Account orders={orders}/>} {page==='promos'&&<Section title='Promociones de la semana' desc={`Cupón ${CODE} y cashback.`}><div className='grid md:grid-cols-2 lg:grid-cols-4 gap-5'>{merchants.filter(m=>m.promo).slice(0,12).map(m=><Card key={m.id} m={m} open={open} add={add}/>)}</div></Section>} {(page==='how'||page==='merchants')&&<Section title={page==='how'?'Cómo funciona':'Para comercios'} desc='Compra local, promoción, cashback y visibilidad para el comercio de proximidad.'><div className='rounded-3xl border p-8 bg-white'>faciliteaGO conecta clientes con comercios locales de Cataluña.</div></Section>}<JuanIA setQ={setQ} open={open}/><footer className='mt-16 border-t bg-zinc-50'><div className='max-w-7xl mx-auto px-4 py-8 flex justify-between'><Logo/><div className='text-sm text-zinc-500'>Marketplace local de Cataluña · Pago simulado</div></div></footer></div>}
