import React,{useMemo,useState}from'react'
import{merchants}from'./data/merchants.js'

const BLUE='#0047BA',AQUA='#2FC2B6',JUAN='https://i.imgur.com/LfWe8VX.png'

function normalize(text=''){return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function fallback(query,catalog){const q=normalize(query);let rows=catalog.filter(x=>normalize(`${x.productName} ${x.merchantName} ${x.sector} ${x.city}`).includes(q));if(q.includes('pinza'))rows=catalog.filter(x=>normalize(x.productName).includes('pinza'));if(q.includes('anillo'))rows=catalog.filter(x=>normalize(x.productName).includes('anillo'));if(q.includes('regalo')||q.includes('nino')||q.includes('niño'))rows=catalog.filter(x=>['Juguetes','Dulces','Regalos','Souvenirs'].includes(x.sector));if(q.includes('menos de 5')||q.includes('barato'))rows=catalog.filter(x=>x.price<=5);rows=rows.slice(0,4);return{answer:rows.length?`Te propongo ${rows.length} opción${rows.length===1?'':'es'} del catálogo faciliteaGO.`:'No encuentro coincidencias claras. Prueba con pinzas, anillo, regalo para niño o menos de 5€.',recommendations:rows.map(x=>({...x,reason:`Encaja con tu búsqueda y está disponible en ${x.merchantName}.`}))}}

export default function GeminiJuanIA(){const catalog=useMemo(()=>merchants.flatMap(m=>m.products.map(p=>({merchantId:m.id,merchantName:m.name,sector:m.sector,city:m.city,address:m.address,productId:p.id,productName:p.name,price:p.price,reason:''}))),[]),[open,setOpen]=useState(false),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[messages,setMessages]=useState([{role:'bot',text:'Soy JuanIA. Pídeme productos, regalos, opciones baratas o rutas. Recomiendo solo productos de faciliteaGO.'}]),[recs,setRecs]=useState([])
 const ask=async(preset)=>{const query=(preset||input).trim();if(!query)return;setInput('');setLoading(true);setMessages(v=>[...v,{role:'user',text:query}]);let payload;try{const r=await fetch('/api/juanias',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});payload=await r.json()}catch{payload=fallback(query,catalog)}if(!payload?.recommendations?.length)payload=fallback(query,catalog);setRecs(payload.recommendations||[]);setMessages(v=>[...v,{role:'bot',text:payload.answer||'Te muestro opciones del catálogo.'}]);setLoading(false)}
 return <><button className='gemini-juanias-button fixed right-5 bottom-5 z-[70] w-16 h-16 rounded-full text-white shadow-2xl grid place-items-center' style={{backgroundColor:BLUE}} onClick={()=>setOpen(true)}>💬</button>{open&&<div className='gemini-juanias-panel fixed right-5 bottom-24 z-[70] w-[calc(100vw-40px)] sm:w-[480px] rounded-[2rem] bg-white border shadow-2xl overflow-hidden'><div className='p-5 text-white flex gap-4 items-center' style={{backgroundColor:BLUE}}><img src={JUAN} className='w-16 h-16 rounded-2xl object-contain bg-white'/><div className='flex-1'><b className='text-xl'>JuanIA</b><div className='text-sm text-white/80'>Recomendador con catálogo e IA</div></div><button onClick={()=>setOpen(false)}>×</button></div><div className='p-4 h-96 overflow-auto space-y-3 bg-zinc-50'>{messages.map((m,i)=><div key={i} className={`max-w-[86%] rounded-3xl px-4 py-3 text-sm ${m.role==='bot'?'bg-white border':'ml-auto text-white'}`} style={m.role==='user'?{backgroundColor:AQUA}:{}}>{m.text}</div>)}{loading&&<div className='rounded-3xl bg-white border px-4 py-3 text-sm'>Buscando en el catálogo...</div>}{recs.map(r=><div key={`${r.merchantId}-${r.productId}`} className='rounded-2xl bg-white border p-3'><b>{r.productName}</b><div className='text-xs text-zinc-500'>{r.merchantName} · {Number(r.price).toFixed(2)}€</div><p className='text-xs text-zinc-600 mt-1'>{r.reason}</p></div>)}</div><div className='p-4 border-t'><div className='flex flex-wrap gap-2 mb-3'>{['Pinzas','Anillo de caramelo','Regalo para niño','Menos de 5€','Ruta por Las Ramblas'].map(p=><button key={p} onClick={()=>ask(p)} className='text-xs font-bold px-3 py-2 rounded-full bg-zinc-100'>{p}</button>)}</div><div className='flex gap-2'><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder='Pregunta a JuanIA...' className='flex-1 rounded-2xl border px-4 py-3'/><button onClick={()=>ask()} disabled={loading} className='px-4 rounded-2xl text-white font-bold disabled:opacity-50' style={{backgroundColor:BLUE}}>Enviar</button></div></div></div>}</>}
