import React,{useMemo,useRef,useState}from'react'
import{merchants}from'./data/merchants.js'

const BLUE='#0047BA',AQUA='#2FC2B6',JUAN='https://i.imgur.com/LfWe8VX.png'

function normalize(text=''){return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function hasAny(text,terms){return terms.some(t=>text.includes(t))}
function scoreRow(row,q){const hay=normalize(`${row.productName} ${row.merchantName} ${row.sector} ${row.city}`),product=normalize(row.productName),sector=normalize(row.sector);let s=0;for(const w of q.split(/\s+/).filter(x=>x.length>2))if(hay.includes(w))s+=2;const tools=hasAny(q,['herramienta','herramientas','reforma','bricolaje','arreglar','montar','destornillador','tornillo','cinta','llave','linterna','ferreteria','ferretería','pintar']);if(tools){if(sector.includes('ferreteria'))s+=30;if(hasAny(product,['destornillador','cinta','llave','guante','brida','cola','linterna','alcayata','pila','metro','tornillo','cuter','cúter','brocha','silicona','pinza']))s+=20;if(sector.includes('dulces')||product.includes('anillo'))s-=100}if(hasAny(q,['anillo','caramelo','gominola','dulce','chuche'])){if(sector.includes('dulces'))s+=25;if(product.includes('anillo'))s+=20}if(hasAny(q,['regalo','niño','nino','juguete','infantil'])){if(['juguetes','dulces','regalos','souvenirs'].includes(row.sector))s+=15}if(hasAny(q,['menos de 5','barato','económico','economico'])&&row.price<=5)s+=15;return s}
function fallback(query,catalog){const q=normalize(query);let rows=catalog.map(x=>({...x,score:scoreRow(x,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.price-b.price);if(!rows.length)rows=catalog.sort((a,b)=>a.price-b.price);rows=rows.slice(0,4);const tools=hasAny(q,['herramienta','reforma','bricolaje','arreglar','montar']);return{answer:tools?'Para una reforma tiraría de ferretería y productos prácticos, no de artículos de regalo. Te dejo opciones reales del catálogo.':`Te propongo ${rows.length} opción${rows.length===1?'':'es'} reales del catálogo faciliteaGO.`,followUp:tools?'¿Quieres algo más orientado a pintar, montar muebles o arreglos pequeños?':'¿Quieres que lo filtre por precio, cercanía o recogida en tienda?',recommendations:rows.map(x=>({...x,reason:tools?`Es útil para bricolaje o pequeñas reparaciones y está disponible en ${x.merchantName}.`:`Encaja con tu búsqueda y está disponible en ${x.merchantName}.`}))}}

export default function GeminiJuanIA(){const catalog=useMemo(()=>merchants.flatMap(m=>m.products.map(p=>({merchantId:m.id,merchantName:m.name,sector:m.sector,city:m.city,address:m.address,productId:p.id,productName:p.name,price:p.price,reason:''}))),[]),[open,setOpen]=useState(false),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[messages,setMessages]=useState([{role:'bot',text:'Soy JuanIA. Cuéntame qué necesitas como se lo contarías a una persona: “voy a hacer una reforma”, “necesito un regalo barato”, “quiero algo dulce para niños”... Yo te recomiendo solo productos reales de faciliteaGO.'}]),[recs,setRecs]=useState([]),[context,setContext]=useState([]);const boxRef=useRef(null)
 const push=(next)=>{setMessages(v=>{const out=[...v,...next];setTimeout(()=>{if(boxRef.current)boxRef.current.scrollTop=boxRef.current.scrollHeight},50);return out})}
 const ask=async(preset)=>{const query=(preset||input).trim();if(!query||loading)return;setInput('');setLoading(true);setRecs([]);push([{role:'user',text:query}]);const history=[...context,{role:'user',text:query}].slice(-8);let payload;try{const r=await fetch('/api/juanias',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,history})});payload=await r.json()}catch{payload=fallback(query,catalog)}if(!payload?.recommendations?.length)payload=fallback(query,catalog);const botText=[payload.answer,payload.followUp].filter(Boolean).join('\n\n');setRecs(payload.recommendations||[]);push([{role:'bot',text:botText||'Te muestro opciones del catálogo.'}]);setContext([...history,{role:'bot',text:botText}].slice(-8));setLoading(false)}
 return <><button className='gemini-juanias-button fixed right-5 bottom-5 z-[70] w-16 h-16 rounded-full text-white shadow-2xl grid place-items-center' style={{backgroundColor:BLUE}} onClick={()=>setOpen(true)}>💬</button>{open&&<div className='gemini-juanias-panel fixed right-5 bottom-24 z-[70] w-[calc(100vw-40px)] sm:w-[500px] rounded-[2rem] bg-white border shadow-2xl overflow-hidden'><div className='p-5 text-white flex gap-4 items-center' style={{backgroundColor:BLUE}}><img src={JUAN} className='w-16 h-16 rounded-2xl object-contain bg-white'/><div className='flex-1'><b className='text-xl'>JuanIA</b><div className='text-sm text-white/80'>Asistente conversacional de compra local</div></div><button onClick={()=>setOpen(false)} className='text-xl'>×</button></div><div ref={boxRef} className='p-4 h-96 overflow-auto space-y-3 bg-zinc-50'>{messages.map((m,i)=><div key={i} className={`max-w-[88%] whitespace-pre-line rounded-3xl px-4 py-3 text-sm leading-relaxed ${m.role==='bot'?'bg-white border':'ml-auto text-white'}`} style={m.role==='user'?{backgroundColor:AQUA}:{}}>{m.text}</div>)}{loading&&<div className='rounded-3xl bg-white border px-4 py-3 text-sm'>Estoy revisando el catálogo y descartando lo que no encaja...</div>}{recs.map(r=><div key={`${r.merchantId}-${r.productId}`} className='rounded-2xl bg-white border p-3'><div className='flex items-start justify-between gap-3'><div><b>{r.productName}</b><div className='text-xs text-zinc-500'>{r.merchantName} · {Number(r.price).toFixed(2)}€ · {r.city||''}</div></div><span className='text-xs font-bold text-teal-700 bg-teal-50 px-2 py-1 rounded-full'>4% cashback</span></div><p className='text-xs text-zinc-600 mt-2'>{r.reason}</p></div>)}</div><div className='p-4 border-t'><div className='flex flex-wrap gap-2 mb-3'>{['Herramientas para reforma','Regalo para niño por menos de 10€','Algo dulce barato','Souvenir cerca de Las Ramblas','Ruta con 3 paradas'].map(p=><button key={p} onClick={()=>ask(p)} className='text-xs font-bold px-3 py-2 rounded-full bg-zinc-100'>{p}</button>)}</div><div className='flex gap-2'><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder='Pregunta como a una persona...' className='flex-1 rounded-2xl border px-4 py-3'/><button onClick={()=>ask()} disabled={loading} className='px-4 rounded-2xl text-white font-bold disabled:opacity-50' style={{backgroundColor:BLUE}}>Enviar</button></div></div></div>}</>}
