import React,{useMemo,useRef,useState}from'react'
import{merchants}from'./data/merchants.js'

const BLUE='#0047BA',AQUA='#2FC2B6',JUAN='https://i.imgur.com/LfWe8VX.png'

function normalize(text=''){return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function hasAny(text,terms){return terms.some(t=>text.includes(t))}
function productImage(i){const ids=['photo-1504148455328-c376907d081c','photo-1582058091505-f87a2e55a40f','photo-1512820790803-83ca734da794','photo-1542291026-7eec264c27ff'];return`https://images.unsplash.com/${ids[i%ids.length]}?auto=format&fit=crop&w=500&h=360&q=80`}
function buildCatalog(){return merchants.flatMap((m,mi)=>m.products.map((p,pi)=>({merchantId:m.id,merchantName:m.name,sector:m.sector,city:m.city,address:m.address,distance:Number(m.distance||99),open:m.open,productId:p.id,productName:p.name,price:Number(p.price),description:p.description||'',image:p.image||p.img||productImage(mi+pi),reason:''})))}
function findItem(catalog,merchantId,productId){return catalog.find(x=>x.merchantId===merchantId&&x.productId===productId)}
function scoreRow(row,q){const hay=normalize(`${row.productName} ${row.merchantName} ${row.sector} ${row.city} ${row.description}`),product=normalize(row.productName),sector=normalize(row.sector);let s=0;for(const w of q.split(/\s+/).filter(x=>x.length>2))if(hay.includes(w))s+=2;const tools=hasAny(q,['herramienta','herramientas','reforma','bricolaje','arreglar','montar','destornillador','tornillo','cinta','llave','linterna','ferreteria','ferretería','pintar']);if(tools){if(sector.includes('ferreteria'))s+=30;if(hasAny(product,['destornillador','cinta','llave','guante','brida','cola','linterna','alcayata','pila','metro','tornillo','cuter','cúter','brocha','silicona','pinza']))s+=20;if(sector.includes('dulces')||product.includes('anillo'))s-=100}if(hasAny(q,['anillo','caramelo','gominola','dulce','chuche'])){if(sector.includes('dulces'))s+=25;if(product.includes('anillo'))s+=20}if(hasAny(q,['regalo','niño','nino','juguete','infantil'])){if(['juguetes','dulces','regalos','souvenirs'].includes(row.sector))s+=15}if(hasAny(q,['menos de 5','barato','económico','economico'])&&row.price<=5)s+=15;return s}
function fallback(query,catalog){const q=normalize(query);let rows=catalog.map(x=>({...x,score:scoreRow(x,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.price-b.price);if(!rows.length)rows=catalog.sort((a,b)=>a.price-b.price);rows=rows.slice(0,4);const tools=hasAny(q,['herramienta','reforma','bricolaje','arreglar','montar']);return{answer:tools?'Para una reforma tiraría de ferretería y productos prácticos. Estas opciones encajan mejor que algo simplemente barato.':`He buscado en el catálogo y estas opciones encajan con lo que pides.`,followUp:tools?'¿Quieres que lo ordene por cercanía, precio o por lo más práctico?':'¿Quieres que lo ordene por cercanía, precio o que añada alguno al carrito?',recommendations:rows.map(x=>({...x,reason:tools?`Útil para bricolaje o pequeñas reparaciones, disponible en ${x.merchantName}.`:`Encaja con tu búsqueda y está disponible en ${x.merchantName}.`}))}}
function readCart(){try{return JSON.parse(localStorage.getItem('fgo_cart'))||[]}catch{return[]}}
function writeCart(cart){localStorage.setItem('fgo_cart',JSON.stringify(cart))}
function detectSort(q){if(hasAny(q,['cercania','cercanía','distancia','cerca','mas cerca','más cerca']))return'distance';if(hasAny(q,['precio','barato','menor precio','mas barato','más barato']))return'price';if(hasAny(q,['abierto','abiertos']))return'open';return''}
function detectAdd(q){return hasAny(q,['añade','anade','agrega','mete','pon','compra'])&&hasAny(q,['carrito','carro','cesta'])}
function pickFromText(q,recs){if(!recs.length)return null;if(hasAny(q,['primero','primera','1']))return recs[0];if(hasAny(q,['segundo','segunda','2']))return recs[1]||recs[0];if(hasAny(q,['tercero','tercera','3']))return recs[2]||recs[0];const exact=recs.find(r=>normalize(q).includes(normalize(r.productName).split(' ')[0])||normalize(q).includes(normalize(r.merchantName).split(' ')[0]));return exact||recs[0]}

export default function GeminiJuanIA(){const catalog=useMemo(buildCatalog,[]),[open,setOpen]=useState(false),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[messages,setMessages]=useState([{role:'bot',text:'Soy JuanIA. Tengo memoria de lo que acabamos de hablar: puedo buscar productos, ordenar los resultados por cercanía o precio y añadir al carrito lo que me pidas.'}]),[recs,setRecs]=useState([]),[context,setContext]=useState([]);const boxRef=useRef(null)
 const push=(next)=>{setMessages(v=>{const out=[...v,...next];setTimeout(()=>{if(boxRef.current)boxRef.current.scrollTop=boxRef.current.scrollHeight},50);return out})}
 const sortCurrent=(mode)=>{let sorted=[...recs];if(mode==='distance')sorted.sort((a,b)=>(a.distance??99)-(b.distance??99));if(mode==='price')sorted.sort((a,b)=>a.price-b.price);if(mode==='open')sorted.sort((a,b)=>(b.open===true)-(a.open===true));setRecs(sorted);return sorted}
 const addItem=(item)=>{if(!item)return false;const merchant=merchants.find(m=>m.id===item.merchantId),source=merchant?.products.find(p=>p.id===item.productId);if(!merchant||!source)return false;const product={...source,image:item.image||source.image||source.img||productImage(1)},id=merchant.id+product.id,cart=readCart(),ex=cart.find(i=>i.id===id);const next=ex?cart.map(i=>i.id===id?{...i,qty:i.qty+1}:i):[...cart,{id,merchant,product,qty:1}];writeCart(next);window.dispatchEvent(new Event('storage'));return true}
 const ask=async(preset)=>{const query=(preset||input).trim();if(!query||loading)return;const q=normalize(query);setInput('');push([{role:'user',text:query}]);
  if(detectAdd(q)){const chosen=pickFromText(q,recs);if(addItem(chosen)){push([{role:'bot',text:`He añadido al carrito: ${chosen.productName} de ${chosen.merchantName}.\n\nMantengo estos resultados por si quieres añadir otro o pasar a pagar.`}]);return}push([{role:'bot',text:'No tengo claro qué producto quieres añadir. Dime, por ejemplo: “añade el primero al carrito” o “añade el destornillador”.'}]);return}
  const sortMode=detectSort(q);if(sortMode&&recs.length){const sorted=sortCurrent(sortMode);const label=sortMode==='distance'?'cercanía':sortMode==='price'?'precio':'comercios abiertos';push([{role:'bot',text:`He reordenado los resultados anteriores por ${label}. El primero ahora es ${sorted[0].productName} en ${sorted[0].merchantName}.`}]);return}
  setLoading(true);setRecs([]);const history=[...context,{role:'user',text:query,lastRecommendations:recs.map(r=>({merchantId:r.merchantId,productId:r.productId,productName:r.productName,merchantName:r.merchantName,price:r.price,distance:r.distance}))}].slice(-8);let payload;try{const r=await fetch('/api/juanias',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,history,lastRecommendations:recs})});payload=await r.json()}catch{payload=fallback(query,catalog)}if(!payload?.recommendations?.length)payload=fallback(query,catalog);const hydrated=(payload.recommendations||[]).map(r=>({...findItem(catalog,r.merchantId,r.productId),...r})).filter(r=>r.productId);const botText=[payload.answer,payload.followUp].filter(Boolean).join('\n\n');setRecs(hydrated);push([{role:'bot',text:botText||'Te muestro opciones del catálogo.'}]);setContext([...history,{role:'bot',text:botText,recommendations:hydrated.slice(0,4)}].slice(-8));setLoading(false)}
 return <><button className='gemini-juanias-button fixed right-5 bottom-5 z-[70] w-16 h-16 rounded-full text-white shadow-2xl grid place-items-center' style={{backgroundColor:BLUE}} onClick={()=>setOpen(true)}>💬</button>{open&&<div className='gemini-juanias-panel fixed right-5 bottom-24 z-[70] w-[calc(100vw-40px)] sm:w-[520px] rounded-[2rem] bg-white border shadow-2xl overflow-hidden'><div className='p-5 text-white flex gap-4 items-center' style={{backgroundColor:BLUE}}><img src={JUAN} className='w-16 h-16 rounded-2xl object-contain bg-white'/><div className='flex-1'><b className='text-xl'>JuanIA</b><div className='text-sm text-white/80'>Asistente con memoria y acciones</div></div><button onClick={()=>setOpen(false)} className='text-xl'>×</button></div><div ref={boxRef} className='p-4 h-96 overflow-auto space-y-3 bg-zinc-50'>{messages.map((m,i)=><div key={i} className={`max-w-[88%] whitespace-pre-line rounded-3xl px-4 py-3 text-sm leading-relaxed ${m.role==='bot'?'bg-white border':'ml-auto text-white'}`} style={m.role==='user'?{backgroundColor:AQUA}:{}}>{m.text}</div>)}{loading&&<div className='rounded-3xl bg-white border px-4 py-3 text-sm'>Estoy revisando el catálogo y el contexto anterior...</div>}{recs.map((r,i)=><div key={`${r.merchantId}-${r.productId}`} className='rounded-2xl bg-white border p-3'><div className='flex items-start justify-between gap-3'><div><b>{i+1}. {r.productName}</b><div className='text-xs text-zinc-500'>{r.merchantName} · {Number(r.price).toFixed(2)}€ · {r.distance??'-'} km</div></div><span className='text-xs font-bold text-teal-700 bg-teal-50 px-2 py-1 rounded-full'>4% cashback</span></div><p className='text-xs text-zinc-600 mt-2'>{r.reason}</p><button onClick={()=>{addItem(r);push([{role:'bot',text:`Añadido al carrito: ${r.productName}.`}])}} className='mt-3 text-xs font-bold px-3 py-2 rounded-full bg-blue-50 text-blue-700'>Añadir al carrito</button></div>)}</div><div className='p-4 border-t'><div className='flex flex-wrap gap-2 mb-3'>{['Herramientas para reforma','Ordénalo por cercanía','Añade el primero al carrito','Regalo para niño por menos de 10€','Más barato primero'].map(p=><button key={p} onClick={()=>ask(p)} className='text-xs font-bold px-3 py-2 rounded-full bg-zinc-100'>{p}</button>)}</div><div className='flex gap-2'><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder='Pide, filtra u ordena lo anterior...' className='flex-1 rounded-2xl border px-4 py-3'/><button onClick={()=>ask()} disabled={loading} className='px-4 rounded-2xl text-white font-bold disabled:opacity-50' style={{backgroundColor:BLUE}}>Enviar</button></div></div></div>}</>}
